image: docker:20.10.12
before_script:
  - chmod og= $ID_RSA
  - apk update && apk add openssh-client
#  - docker login -u "tomek" -p "tomek" registry-server.homelab.tslab.live
services:
  - docker:20.10.12-dind

stages:
  - build
  - deploy

.build-tmpl:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        ENV: "production"
        ENV_TAG: "prod"
    - if: $CI_COMMIT_REF_NAME == "develop"
      variables:
        ENV: "development"
        ENV_TAG: "dev"
  environment:
    name: $ENV

build:
  extends: .build-tmpl
  stage: build
  script:
    - echo "Building client and server..."
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_REPOSITORY_URL
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/tomek/apps && sudo rm -rf moviesdb/"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/tomek/apps && mkdir moviesdb/"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/tomek/apps && git clone $CI_REPOSITORY_URL"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/tomek/apps/moviesdb && git checkout $CI_COMMIT_REF_NAME"
    #    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/tomek/apps/moviesdb/client && cp /home/tomek/apps/env/moviesdb/client/.env.$ENV_TAG ."
    #    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/tomek/apps/moviesdb/server && cp /home/tomek/apps/env/moviesdb/server/.env.$ENV_TAG ."
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd apps/moviesdb && git checkout $CI_COMMIT_REF_NAME && docker-compose -f docker-compose.$ENV_TAG.yml build"

deploy:
  stage: deploy
  extends: .build-tmpl
  script:
    - echo "Deploying client and server..."
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd apps/moviesdb && git checkout $CI_COMMIT_REF_NAME && docker stack rm moviesdb-$ENV_TAG || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd apps/moviesdb && git checkout $CI_COMMIT_REF_NAME && docker stack deploy -c stack.$ENV_TAG.yml moviesdb-$ENV_TAG"
